services:
  consul:
    image: hashicorp/consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"

  consul-init:
    image: hashicorp/consul:1.15
    container_name: consul-init
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    command: >
      sh -c "
      sleep 2 &&
      consul kv put hazelcast/config '{\"cluster_name\":\"dev-cluster\",\"members\":[\"hazelcast1:5701\",\"hazelcast2:5701\",\"hazelcast3:5701\"]}' &&
      consul kv put kafka/config '{\"brokers\":\"kafka:9092\",\"topic\":\"transactions\"}'
      "

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Using Kraft mode to avoid needing Zookeeper
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092
            --list",
        ] # list all existing topics via shell command, either 0 or 1+
      interval: 5s
      timeout: 5s
      retries: 5
  facade:
    image: facade-service:latest
    container_name: facade
    build:
      context: .
      dockerfile: facade/Dockerfile
    ports:
      - "8080:8000"
    environment:
      - SERVICE_ID=facade1
      - SERVICE_HOST=facade
      - SERVICE_PORT=8000
      - CONSUL_URL=http://consul:8500
    depends_on:
      kafka:
        condition: service_healthy
      consul-init:
        condition: service_completed_successfully

  logging1:
    image: logging-service:latest
    container_name: logging1
    build:
      context: .
      dockerfile: logging_service/Dockerfile
    environment:
      - SERVICE_ID=logging1
      - SERVICE_HOST=logging1
      - SERVICE_PORT=8000
      - CONSUL_URL=http://consul:8500
    depends_on:
      hazelcast1:
        condition: service_healthy
      consul-init:
        condition: service_completed_successfully

  logging2:
    image: logging-service:latest
    container_name: logging2
    build:
      context: .
      dockerfile: logging_service/Dockerfile
    environment:
      - SERVICE_ID=logging2
      - SERVICE_HOST=logging2
      - SERVICE_PORT=8000
      - CONSUL_URL=http://consul:8500
    depends_on:
      hazelcast1:
        condition: service_healthy
      consul-init:
        condition: service_completed_successfully

  logging3:
    image: logging-service:latest
    container_name: logging3
    build:
      context: .
      dockerfile: logging_service/Dockerfile
    environment:
      - SERVICE_ID=logging3
      - SERVICE_HOST=logging3
      - SERVICE_PORT=8000
      - CONSUL_URL=http://consul:8500
    depends_on:
      hazelcast1:
        condition: service_healthy
      consul-init:
        condition: service_completed_successfully

  counter_service:
    image: counter-service:latest
    container_name: counter_service
    build:
      context: .
      dockerfile: counter_service/Dockerfile
    environment:
      - DB_URL=postgresql://user:password@postgres_db:5432/counter_db
      - SERVICE_ID=counter1
      - SERVICE_HOST=counter_service
      - SERVICE_PORT=8000
      - CONSUL_URL=http://consul:8500
    depends_on:
      postgres_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-init:
        condition: service_completed_successfully

  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: counter_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d counter_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  hazelcast1:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast1
    ports:
      - "5701:5701"
    volumes:
      - ./hazelcast.yaml:/opt/hazelcast/config/hazelcast.yaml
    environment:
      - HZ_CLUSTERNAME=dev-cluster
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config/hazelcast.yaml
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://127.0.0.1:5701/hazelcast/health/node-state" ]
      interval: 10s
      timeout: 5s
      retries: 5

  hazelcast2:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast2
    ports:
      - "5702:5701"
    volumes:
      - ./hazelcast.yaml:/opt/hazelcast/config/hazelcast.yaml
    environment:
      - HZ_CLUSTERNAME=dev-cluster
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config/hazelcast.yaml
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://127.0.0.1:5701/hazelcast/health/node-state" ]
      interval: 10s
      timeout: 5s
      retries: 5

  hazelcast3:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast3
    ports:
      - "5703:5701"
    volumes:
      - ./hazelcast.yaml:/opt/hazelcast/config/hazelcast.yaml
    environment:
      - HZ_CLUSTERNAME=dev-cluster
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config/hazelcast.yaml
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://127.0.0.1:5701/hazelcast/health/node-state" ]
      interval: 10s
      timeout: 5s
      retries: 5

  management-center:
    image: hazelcast/management-center:5.3
    container_name: management-center
    ports:
      - "8081:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev-cluster
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast1,hazelcast2,hazelcast3
